"""Translatable display labels; keys remain immutable bundled IANA identities.
Arabic names use Unicode CLDR via Babel (see locale/NOTICE.txt)."""
from .settings_sections import N_

TIMEZONE_LABELS = {
	'Africa/Abidjan': N_('Africa / Abidjan'),
	'Africa/Accra': N_('Africa / Accra'),
	'Africa/Addis_Ababa': N_('Africa / Addis Ababa'),
	'Africa/Algiers': N_('Africa / Algiers'),
	'Africa/Asmara': N_('Africa / Asmara'),
	'Africa/Asmera': N_('Africa / Asmera'),
	'Africa/Bamako': N_('Africa / Bamako'),
	'Africa/Bangui': N_('Africa / Bangui'),
	'Africa/Banjul': N_('Africa / Banjul'),
	'Africa/Bissau': N_('Africa / Bissau'),
	'Africa/Blantyre': N_('Africa / Blantyre'),
	'Africa/Brazzaville': N_('Africa / Brazzaville'),
	'Africa/Bujumbura': N_('Africa / Bujumbura'),
	'Africa/Cairo': N_('Africa / Cairo'),
	'Africa/Casablanca': N_('Africa / Casablanca'),
	'Africa/Ceuta': N_('Africa / Ceuta'),
	'Africa/Conakry': N_('Africa / Conakry'),
	'Africa/Dakar': N_('Africa / Dakar'),
	'Africa/Dar_es_Salaam': N_('Africa / Dar es Salaam'),
	'Africa/Djibouti': N_('Africa / Djibouti'),
	'Africa/Douala': N_('Africa / Douala'),
	'Africa/El_Aaiun': N_('Africa / El Aaiun'),
	'Africa/Freetown': N_('Africa / Freetown'),
	'Africa/Gaborone': N_('Africa / Gaborone'),
	'Africa/Harare': N_('Africa / Harare'),
	'Africa/Johannesburg': N_('Africa / Johannesburg'),
	'Africa/Juba': N_('Africa / Juba'),
	'Africa/Kampala': N_('Africa / Kampala'),
	'Africa/Khartoum': N_('Africa / Khartoum'),
	'Africa/Kigali': N_('Africa / Kigali'),
	'Africa/Kinshasa': N_('Africa / Kinshasa'),
	'Africa/Lagos': N_('Africa / Lagos'),
	'Africa/Libreville': N_('Africa / Libreville'),
	'Africa/Lome': N_('Africa / Lome'),
	'Africa/Luanda': N_('Africa / Luanda'),
	'Africa/Lubumbashi': N_('Africa / Lubumbashi'),
	'Africa/Lusaka': N_('Africa / Lusaka'),
	'Africa/Malabo': N_('Africa / Malabo'),
	'Africa/Maputo': N_('Africa / Maputo'),
	'Africa/Maseru': N_('Africa / Maseru'),
	'Africa/Mbabane': N_('Africa / Mbabane'),
	'Africa/Mogadishu': N_('Africa / Mogadishu'),
	'Africa/Monrovia': N_('Africa / Monrovia'),
	'Africa/Nairobi': N_('Africa / Nairobi'),
	'Africa/Ndjamena': N_('Africa / Ndjamena'),
	'Africa/Niamey': N_('Africa / Niamey'),
	'Africa/Nouakchott': N_('Africa / Nouakchott'),
	'Africa/Ouagadougou': N_('Africa / Ouagadougou'),
	'Africa/Porto-Novo': N_('Africa / Porto-Novo'),
	'Africa/Sao_Tome': N_('Africa / Sao Tome'),
	'Africa/Timbuktu': N_('Africa / Timbuktu'),
	'Africa/Tripoli': N_('Africa / Tripoli'),
	'Africa/Tunis': N_('Africa / Tunis'),
	'Africa/Windhoek': N_('Africa / Windhoek'),
	'America/Adak': N_('America / Adak'),
	'America/Anchorage': N_('America / Anchorage'),
	'America/Anguilla': N_('America / Anguilla'),
	'America/Antigua': N_('America / Antigua'),
	'America/Araguaina': N_('America / Araguaina'),
	'America/Argentina/Buenos_Aires': N_('America / Argentina / Buenos Aires'),
	'America/Argentina/Catamarca': N_('America / Argentina / Catamarca'),
	'America/Argentina/ComodRivadavia': N_('America / Argentina / ComodRivadavia'),
	'America/Argentina/Cordoba': N_('America / Argentina / Cordoba'),
	'America/Argentina/Jujuy': N_('America / Argentina / Jujuy'),
	'America/Argentina/La_Rioja': N_('America / Argentina / La Rioja'),
	'America/Argentina/Mendoza': N_('America / Argentina / Mendoza'),
	'America/Argentina/Rio_Gallegos': N_('America / Argentina / Rio Gallegos'),
	'America/Argentina/Salta': N_('America / Argentina / Salta'),
	'America/Argentina/San_Juan': N_('America / Argentina / San Juan'),
	'America/Argentina/San_Luis': N_('America / Argentina / San Luis'),
	'America/Argentina/Tucuman': N_('America / Argentina / Tucuman'),
	'America/Argentina/Ushuaia': N_('America / Argentina / Ushuaia'),
	'America/Aruba': N_('America / Aruba'),
	'America/Asuncion': N_('America / Asuncion'),
	'America/Atikokan': N_('America / Atikokan'),
	'America/Atka': N_('America / Atka'),
	'America/Bahia': N_('America / Bahia'),
	'America/Bahia_Banderas': N_('America / Bahia Banderas'),
	'America/Barbados': N_('America / Barbados'),
	'America/Belem': N_('America / Belem'),
	'America/Belize': N_('America / Belize'),
	'America/Blanc-Sablon': N_('America / Blanc-Sablon'),
	'America/Boa_Vista': N_('America / Boa Vista'),
	'America/Bogota': N_('America / Bogota'),
	'America/Boise': N_('America / Boise'),
	'America/Buenos_Aires': N_('America / Buenos Aires'),
	'America/Cambridge_Bay': N_('America / Cambridge Bay'),
	'America/Campo_Grande': N_('America / Campo Grande'),
	'America/Cancun': N_('America / Cancun'),
	'America/Caracas': N_('America / Caracas'),
	'America/Catamarca': N_('America / Catamarca'),
	'America/Cayenne': N_('America / Cayenne'),
	'America/Cayman': N_('America / Cayman'),
	'America/Chicago': N_('America / Chicago'),
	'America/Chihuahua': N_('America / Chihuahua'),
	'America/Ciudad_Juarez': N_('America / Ciudad Juarez'),
	'America/Coral_Harbour': N_('America / Coral Harbour'),
	'America/Cordoba': N_('America / Cordoba'),
	'America/Costa_Rica': N_('America / Costa Rica'),
	'America/Coyhaique': N_('America / Coyhaique'),
	'America/Creston': N_('America / Creston'),
	'America/Cuiaba': N_('America / Cuiaba'),
	'America/Curacao': N_('America / Curacao'),
	'America/Danmarkshavn': N_('America / Danmarkshavn'),
	'America/Dawson': N_('America / Dawson'),
	'America/Dawson_Creek': N_('America / Dawson Creek'),
	'America/Denver': N_('America / Denver'),
	'America/Detroit': N_('America / Detroit'),
	'America/Dominica': N_('America / Dominica'),
	'America/Edmonton': N_('America / Edmonton'),
	'America/Eirunepe': N_('America / Eirunepe'),
	'America/El_Salvador': N_('America / El Salvador'),
	'America/Ensenada': N_('America / Ensenada'),
	'America/Fort_Nelson': N_('America / Fort Nelson'),
	'America/Fort_Wayne': N_('America / Fort Wayne'),
	'America/Fortaleza': N_('America / Fortaleza'),
	'America/Glace_Bay': N_('America / Glace Bay'),
	'America/Godthab': N_('America / Godthab'),
	'America/Goose_Bay': N_('America / Goose Bay'),
	'America/Grand_Turk': N_('America / Grand Turk'),
	'America/Grenada': N_('America / Grenada'),
	'America/Guadeloupe': N_('America / Guadeloupe'),
	'America/Guatemala': N_('America / Guatemala'),
	'America/Guayaquil': N_('America / Guayaquil'),
	'America/Guyana': N_('America / Guyana'),
	'America/Halifax': N_('America / Halifax'),
	'America/Havana': N_('America / Havana'),
	'America/Hermosillo': N_('America / Hermosillo'),
	'America/Indiana/Indianapolis': N_('America / Indiana / Indianapolis'),
	'America/Indiana/Knox': N_('America / Indiana / Knox'),
	'America/Indiana/Marengo': N_('America / Indiana / Marengo'),
	'America/Indiana/Petersburg': N_('America / Indiana / Petersburg'),
	'America/Indiana/Tell_City': N_('America / Indiana / Tell City'),
	'America/Indiana/Vevay': N_('America / Indiana / Vevay'),
	'America/Indiana/Vincennes': N_('America / Indiana / Vincennes'),
	'America/Indiana/Winamac': N_('America / Indiana / Winamac'),
	'America/Indianapolis': N_('America / Indianapolis'),
	'America/Inuvik': N_('America / Inuvik'),
	'America/Iqaluit': N_('America / Iqaluit'),
	'America/Jamaica': N_('America / Jamaica'),
	'America/Jujuy': N_('America / Jujuy'),
	'America/Juneau': N_('America / Juneau'),
	'America/Kentucky/Louisville': N_('America / Kentucky / Louisville'),
	'America/Kentucky/Monticello': N_('America / Kentucky / Monticello'),
	'America/Knox_IN': N_('America / Knox IN'),
	'America/Kralendijk': N_('America / Kralendijk'),
	'America/La_Paz': N_('America / La Paz'),
	'America/Lima': N_('America / Lima'),
	'America/Los_Angeles': N_('America / Los Angeles'),
	'America/Louisville': N_('America / Louisville'),
	'America/Lower_Princes': N_('America / Lower Princes'),
	'America/Maceio': N_('America / Maceio'),
	'America/Managua': N_('America / Managua'),
	'America/Manaus': N_('America / Manaus'),
	'America/Marigot': N_('America / Marigot'),
	'America/Martinique': N_('America / Martinique'),
	'America/Matamoros': N_('America / Matamoros'),
	'America/Mazatlan': N_('America / Mazatlan'),
	'America/Mendoza': N_('America / Mendoza'),
	'America/Menominee': N_('America / Menominee'),
	'America/Merida': N_('America / Merida'),
	'America/Metlakatla': N_('America / Metlakatla'),
	'America/Mexico_City': N_('America / Mexico City'),
	'America/Miquelon': N_('America / Miquelon'),
	'America/Moncton': N_('America / Moncton'),
	'America/Monterrey': N_('America / Monterrey'),
	'America/Montevideo': N_('America / Montevideo'),
	'America/Montreal': N_('America / Montreal'),
	'America/Montserrat': N_('America / Montserrat'),
	'America/Nassau': N_('America / Nassau'),
	'America/New_York': N_('America / New York'),
	'America/Nipigon': N_('America / Nipigon'),
	'America/Nome': N_('America / Nome'),
	'America/Noronha': N_('America / Noronha'),
	'America/North_Dakota/Beulah': N_('America / North Dakota / Beulah'),
	'America/North_Dakota/Center': N_('America / North Dakota / Center'),
	'America/North_Dakota/New_Salem': N_('America / North Dakota / New Salem'),
	'America/Nuuk': N_('America / Nuuk'),
	'America/Ojinaga': N_('America / Ojinaga'),
	'America/Panama': N_('America / Panama'),
	'America/Pangnirtung': N_('America / Pangnirtung'),
	'America/Paramaribo': N_('America / Paramaribo'),
	'America/Phoenix': N_('America / Phoenix'),
	'America/Port-au-Prince': N_('America / Port-au-Prince'),
	'America/Port_of_Spain': N_('America / Port of Spain'),
	'America/Porto_Acre': N_('America / Porto Acre'),
	'America/Porto_Velho': N_('America / Porto Velho'),
	'America/Puerto_Rico': N_('America / Puerto Rico'),
	'America/Punta_Arenas': N_('America / Punta Arenas'),
	'America/Rainy_River': N_('America / Rainy River'),
	'America/Rankin_Inlet': N_('America / Rankin Inlet'),
	'America/Recife': N_('America / Recife'),
	'America/Regina': N_('America / Regina'),
	'America/Resolute': N_('America / Resolute'),
	'America/Rio_Branco': N_('America / Rio Branco'),
	'America/Rosario': N_('America / Rosario'),
	'America/Santa_Isabel': N_('America / Santa Isabel'),
	'America/Santarem': N_('America / Santarem'),
	'America/Santiago': N_('America / Santiago'),
	'America/Santo_Domingo': N_('America / Santo Domingo'),
	'America/Sao_Paulo': N_('America / Sao Paulo'),
	'America/Scoresbysund': N_('America / Scoresbysund'),
	'America/Shiprock': N_('America / Shiprock'),
	'America/Sitka': N_('America / Sitka'),
	'America/St_Barthelemy': N_('America / St Barthelemy'),
	'America/St_Johns': N_('America / St Johns'),
	'America/St_Kitts': N_('America / St Kitts'),
	'America/St_Lucia': N_('America / St Lucia'),
	'America/St_Thomas': N_('America / St Thomas'),
	'America/St_Vincent': N_('America / St Vincent'),
	'America/Swift_Current': N_('America / Swift Current'),
	'America/Tegucigalpa': N_('America / Tegucigalpa'),
	'America/Thule': N_('America / Thule'),
	'America/Thunder_Bay': N_('America / Thunder Bay'),
	'America/Tijuana': N_('America / Tijuana'),
	'America/Toronto': N_('America / Toronto'),
	'America/Tortola': N_('America / Tortola'),
	'America/Vancouver': N_('America / Vancouver'),
	'America/Virgin': N_('America / Virgin'),
	'America/Whitehorse': N_('America / Whitehorse'),
	'America/Winnipeg': N_('America / Winnipeg'),
	'America/Yakutat': N_('America / Yakutat'),
	'America/Yellowknife': N_('America / Yellowknife'),
	'Antarctica/Casey': N_('Antarctica / Casey'),
	'Antarctica/Davis': N_('Antarctica / Davis'),
	'Antarctica/DumontDUrville': N_('Antarctica / DumontDUrville'),
	'Antarctica/Macquarie': N_('Antarctica / Macquarie'),
	'Antarctica/Mawson': N_('Antarctica / Mawson'),
	'Antarctica/McMurdo': N_('Antarctica / McMurdo'),
	'Antarctica/Palmer': N_('Antarctica / Palmer'),
	'Antarctica/Rothera': N_('Antarctica / Rothera'),
	'Antarctica/South_Pole': N_('Antarctica / South Pole'),
	'Antarctica/Syowa': N_('Antarctica / Syowa'),
	'Antarctica/Troll': N_('Antarctica / Troll'),
	'Antarctica/Vostok': N_('Antarctica / Vostok'),
	'Arctic/Longyearbyen': N_('Arctic / Longyearbyen'),
	'Asia/Aden': N_('Asia / Aden'),
	'Asia/Almaty': N_('Asia / Almaty'),
	'Asia/Amman': N_('Asia / Amman'),
	'Asia/Anadyr': N_('Asia / Anadyr'),
	'Asia/Aqtau': N_('Asia / Aqtau'),
	'Asia/Aqtobe': N_('Asia / Aqtobe'),
	'Asia/Ashgabat': N_('Asia / Ashgabat'),
	'Asia/Ashkhabad': N_('Asia / Ashkhabad'),
	'Asia/Atyrau': N_('Asia / Atyrau'),
	'Asia/Baghdad': N_('Asia / Baghdad'),
	'Asia/Bahrain': N_('Asia / Bahrain'),
	'Asia/Baku': N_('Asia / Baku'),
	'Asia/Bangkok': N_('Asia / Bangkok'),
	'Asia/Barnaul': N_('Asia / Barnaul'),
	'Asia/Beirut': N_('Asia / Beirut'),
	'Asia/Bishkek': N_('Asia / Bishkek'),
	'Asia/Brunei': N_('Asia / Brunei'),
	'Asia/Calcutta': N_('Asia / Calcutta'),
	'Asia/Chita': N_('Asia / Chita'),
	'Asia/Choibalsan': N_('Asia / Choibalsan'),
	'Asia/Chongqing': N_('Asia / Chongqing'),
	'Asia/Chungking': N_('Asia / Chungking'),
	'Asia/Colombo': N_('Asia / Colombo'),
	'Asia/Dacca': N_('Asia / Dacca'),
	'Asia/Damascus': N_('Asia / Damascus'),
	'Asia/Dhaka': N_('Asia / Dhaka'),
	'Asia/Dili': N_('Asia / Dili'),
	'Asia/Dubai': N_('Asia / Dubai'),
	'Asia/Dushanbe': N_('Asia / Dushanbe'),
	'Asia/Famagusta': N_('Asia / Famagusta'),
	'Asia/Gaza': N_('Asia / Gaza'),
	'Asia/Harbin': N_('Asia / Harbin'),
	'Asia/Hebron': N_('Asia / Hebron'),
	'Asia/Ho_Chi_Minh': N_('Asia / Ho Chi Minh'),
	'Asia/Hong_Kong': N_('Asia / Hong Kong'),
	'Asia/Hovd': N_('Asia / Hovd'),
	'Asia/Irkutsk': N_('Asia / Irkutsk'),
	'Asia/Istanbul': N_('Asia / Istanbul'),
	'Asia/Jakarta': N_('Asia / Jakarta'),
	'Asia/Jayapura': N_('Asia / Jayapura'),
	'Asia/Jerusalem': N_('Asia / Jerusalem'),
	'Asia/Kabul': N_('Asia / Kabul'),
	'Asia/Kamchatka': N_('Asia / Kamchatka'),
	'Asia/Karachi': N_('Asia / Karachi'),
	'Asia/Kashgar': N_('Asia / Kashgar'),
	'Asia/Kathmandu': N_('Asia / Kathmandu'),
	'Asia/Katmandu': N_('Asia / Katmandu'),
	'Asia/Khandyga': N_('Asia / Khandyga'),
	'Asia/Kolkata': N_('Asia / Kolkata'),
	'Asia/Krasnoyarsk': N_('Asia / Krasnoyarsk'),
	'Asia/Kuala_Lumpur': N_('Asia / Kuala Lumpur'),
	'Asia/Kuching': N_('Asia / Kuching'),
	'Asia/Kuwait': N_('Asia / Kuwait'),
	'Asia/Macao': N_('Asia / Macao'),
	'Asia/Macau': N_('Asia / Macau'),
	'Asia/Magadan': N_('Asia / Magadan'),
	'Asia/Makassar': N_('Asia / Makassar'),
	'Asia/Manila': N_('Asia / Manila'),
	'Asia/Muscat': N_('Asia / Muscat'),
	'Asia/Nicosia': N_('Asia / Nicosia'),
	'Asia/Novokuznetsk': N_('Asia / Novokuznetsk'),
	'Asia/Novosibirsk': N_('Asia / Novosibirsk'),
	'Asia/Omsk': N_('Asia / Omsk'),
	'Asia/Oral': N_('Asia / Oral'),
	'Asia/Phnom_Penh': N_('Asia / Phnom Penh'),
	'Asia/Pontianak': N_('Asia / Pontianak'),
	'Asia/Pyongyang': N_('Asia / Pyongyang'),
	'Asia/Qatar': N_('Asia / Qatar'),
	'Asia/Qostanay': N_('Asia / Qostanay'),
	'Asia/Qyzylorda': N_('Asia / Qyzylorda'),
	'Asia/Rangoon': N_('Asia / Rangoon'),
	'Asia/Riyadh': N_('Asia / Riyadh'),
	'Asia/Saigon': N_('Asia / Saigon'),
	'Asia/Sakhalin': N_('Asia / Sakhalin'),
	'Asia/Samarkand': N_('Asia / Samarkand'),
	'Asia/Seoul': N_('Asia / Seoul'),
	'Asia/Shanghai': N_('Asia / Shanghai'),
	'Asia/Singapore': N_('Asia / Singapore'),
	'Asia/Srednekolymsk': N_('Asia / Srednekolymsk'),
	'Asia/Taipei': N_('Asia / Taipei'),
	'Asia/Tashkent': N_('Asia / Tashkent'),
	'Asia/Tbilisi': N_('Asia / Tbilisi'),
	'Asia/Tehran': N_('Asia / Tehran'),
	'Asia/Tel_Aviv': N_('Asia / Tel Aviv'),
	'Asia/Thimbu': N_('Asia / Thimbu'),
	'Asia/Thimphu': N_('Asia / Thimphu'),
	'Asia/Tokyo': N_('Asia / Tokyo'),
	'Asia/Tomsk': N_('Asia / Tomsk'),
	'Asia/Ujung_Pandang': N_('Asia / Ujung Pandang'),
	'Asia/Ulaanbaatar': N_('Asia / Ulaanbaatar'),
	'Asia/Ulan_Bator': N_('Asia / Ulan Bator'),
	'Asia/Urumqi': N_('Asia / Urumqi'),
	'Asia/Ust-Nera': N_('Asia / Ust-Nera'),
	'Asia/Vientiane': N_('Asia / Vientiane'),
	'Asia/Vladivostok': N_('Asia / Vladivostok'),
	'Asia/Yakutsk': N_('Asia / Yakutsk'),
	'Asia/Yangon': N_('Asia / Yangon'),
	'Asia/Yekaterinburg': N_('Asia / Yekaterinburg'),
	'Asia/Yerevan': N_('Asia / Yerevan'),
	'Atlantic/Azores': N_('Atlantic / Azores'),
	'Atlantic/Bermuda': N_('Atlantic / Bermuda'),
	'Atlantic/Canary': N_('Atlantic / Canary'),
	'Atlantic/Cape_Verde': N_('Atlantic / Cape Verde'),
	'Atlantic/Faeroe': N_('Atlantic / Faeroe'),
	'Atlantic/Faroe': N_('Atlantic / Faroe'),
	'Atlantic/Jan_Mayen': N_('Atlantic / Jan Mayen'),
	'Atlantic/Madeira': N_('Atlantic / Madeira'),
	'Atlantic/Reykjavik': N_('Atlantic / Reykjavik'),
	'Atlantic/South_Georgia': N_('Atlantic / South Georgia'),
	'Atlantic/St_Helena': N_('Atlantic / St Helena'),
	'Atlantic/Stanley': N_('Atlantic / Stanley'),
	'Australia/ACT': N_('Australia / ACT'),
	'Australia/Adelaide': N_('Australia / Adelaide'),
	'Australia/Brisbane': N_('Australia / Brisbane'),
	'Australia/Broken_Hill': N_('Australia / Broken Hill'),
	'Australia/Canberra': N_('Australia / Canberra'),
	'Australia/Currie': N_('Australia / Currie'),
	'Australia/Darwin': N_('Australia / Darwin'),
	'Australia/Eucla': N_('Australia / Eucla'),
	'Australia/Hobart': N_('Australia / Hobart'),
	'Australia/LHI': N_('Australia / LHI'),
	'Australia/Lindeman': N_('Australia / Lindeman'),
	'Australia/Lord_Howe': N_('Australia / Lord Howe'),
	'Australia/Melbourne': N_('Australia / Melbourne'),
	'Australia/NSW': N_('Australia / NSW'),
	'Australia/North': N_('Australia / North'),
	'Australia/Perth': N_('Australia / Perth'),
	'Australia/Queensland': N_('Australia / Queensland'),
	'Australia/South': N_('Australia / South'),
	'Australia/Sydney': N_('Australia / Sydney'),
	'Australia/Tasmania': N_('Australia / Tasmania'),
	'Australia/Victoria': N_('Australia / Victoria'),
	'Australia/West': N_('Australia / West'),
	'Australia/Yancowinna': N_('Australia / Yancowinna'),
	'Brazil/Acre': N_('Brazil / Acre'),
	'Brazil/DeNoronha': N_('Brazil / DeNoronha'),
	'Brazil/East': N_('Brazil / East'),
	'Brazil/West': N_('Brazil / West'),
	'CET': N_('CET'),
	'CST6CDT': N_('CST6CDT'),
	'Canada/Atlantic': N_('Canada / Atlantic'),
	'Canada/Central': N_('Canada / Central'),
	'Canada/Eastern': N_('Canada / Eastern'),
	'Canada/Mountain': N_('Canada / Mountain'),
	'Canada/Newfoundland': N_('Canada / Newfoundland'),
	'Canada/Pacific': N_('Canada / Pacific'),
	'Canada/Saskatchewan': N_('Canada / Saskatchewan'),
	'Canada/Yukon': N_('Canada / Yukon'),
	'Chile/Continental': N_('Chile / Continental'),
	'Chile/EasterIsland': N_('Chile / EasterIsland'),
	'Cuba': N_('Cuba'),
	'EET': N_('EET'),
	'EST': N_('EST'),
	'EST5EDT': N_('EST5EDT'),
	'Egypt': N_('Egypt'),
	'Eire': N_('Eire'),
	'Etc/GMT': N_('Etc / GMT'),
	'Etc/GMT+0': N_('Etc / GMT+0'),
	'Etc/GMT+1': N_('Etc / GMT+1'),
	'Etc/GMT+10': N_('Etc / GMT+10'),
	'Etc/GMT+11': N_('Etc / GMT+11'),
	'Etc/GMT+12': N_('Etc / GMT+12'),
	'Etc/GMT+2': N_('Etc / GMT+2'),
	'Etc/GMT+3': N_('Etc / GMT+3'),
	'Etc/GMT+4': N_('Etc / GMT+4'),
	'Etc/GMT+5': N_('Etc / GMT+5'),
	'Etc/GMT+6': N_('Etc / GMT+6'),
	'Etc/GMT+7': N_('Etc / GMT+7'),
	'Etc/GMT+8': N_('Etc / GMT+8'),
	'Etc/GMT+9': N_('Etc / GMT+9'),
	'Etc/GMT-0': N_('Etc / GMT-0'),
	'Etc/GMT-1': N_('Etc / GMT-1'),
	'Etc/GMT-10': N_('Etc / GMT-10'),
	'Etc/GMT-11': N_('Etc / GMT-11'),
	'Etc/GMT-12': N_('Etc / GMT-12'),
	'Etc/GMT-13': N_('Etc / GMT-13'),
	'Etc/GMT-14': N_('Etc / GMT-14'),
	'Etc/GMT-2': N_('Etc / GMT-2'),
	'Etc/GMT-3': N_('Etc / GMT-3'),
	'Etc/GMT-4': N_('Etc / GMT-4'),
	'Etc/GMT-5': N_('Etc / GMT-5'),
	'Etc/GMT-6': N_('Etc / GMT-6'),
	'Etc/GMT-7': N_('Etc / GMT-7'),
	'Etc/GMT-8': N_('Etc / GMT-8'),
	'Etc/GMT-9': N_('Etc / GMT-9'),
	'Etc/GMT0': N_('Etc / GMT0'),
	'Etc/Greenwich': N_('Etc / Greenwich'),
	'Etc/UCT': N_('Etc / UCT'),
	'Etc/UTC': N_('Etc / UTC'),
	'Etc/Universal': N_('Etc / Universal'),
	'Etc/Zulu': N_('Etc / Zulu'),
	'Europe/Amsterdam': N_('Europe / Amsterdam'),
	'Europe/Andorra': N_('Europe / Andorra'),
	'Europe/Astrakhan': N_('Europe / Astrakhan'),
	'Europe/Athens': N_('Europe / Athens'),
	'Europe/Belfast': N_('Europe / Belfast'),
	'Europe/Belgrade': N_('Europe / Belgrade'),
	'Europe/Berlin': N_('Europe / Berlin'),
	'Europe/Bratislava': N_('Europe / Bratislava'),
	'Europe/Brussels': N_('Europe / Brussels'),
	'Europe/Bucharest': N_('Europe / Bucharest'),
	'Europe/Budapest': N_('Europe / Budapest'),
	'Europe/Busingen': N_('Europe / Busingen'),
	'Europe/Chisinau': N_('Europe / Chisinau'),
	'Europe/Copenhagen': N_('Europe / Copenhagen'),
	'Europe/Dublin': N_('Europe / Dublin'),
	'Europe/Gibraltar': N_('Europe / Gibraltar'),
	'Europe/Guernsey': N_('Europe / Guernsey'),
	'Europe/Helsinki': N_('Europe / Helsinki'),
	'Europe/Isle_of_Man': N_('Europe / Isle of Man'),
	'Europe/Istanbul': N_('Europe / Istanbul'),
	'Europe/Jersey': N_('Europe / Jersey'),
	'Europe/Kaliningrad': N_('Europe / Kaliningrad'),
	'Europe/Kiev': N_('Europe / Kiev'),
	'Europe/Kirov': N_('Europe / Kirov'),
	'Europe/Kyiv': N_('Europe / Kyiv'),
	'Europe/Lisbon': N_('Europe / Lisbon'),
	'Europe/Ljubljana': N_('Europe / Ljubljana'),
	'Europe/London': N_('Europe / London'),
	'Europe/Luxembourg': N_('Europe / Luxembourg'),
	'Europe/Madrid': N_('Europe / Madrid'),
	'Europe/Malta': N_('Europe / Malta'),
	'Europe/Mariehamn': N_('Europe / Mariehamn'),
	'Europe/Minsk': N_('Europe / Minsk'),
	'Europe/Monaco': N_('Europe / Monaco'),
	'Europe/Moscow': N_('Europe / Moscow'),
	'Europe/Nicosia': N_('Europe / Nicosia'),
	'Europe/Oslo': N_('Europe / Oslo'),
	'Europe/Paris': N_('Europe / Paris'),
	'Europe/Podgorica': N_('Europe / Podgorica'),
	'Europe/Prague': N_('Europe / Prague'),
	'Europe/Riga': N_('Europe / Riga'),
	'Europe/Rome': N_('Europe / Rome'),
	'Europe/Samara': N_('Europe / Samara'),
	'Europe/San_Marino': N_('Europe / San Marino'),
	'Europe/Sarajevo': N_('Europe / Sarajevo'),
	'Europe/Saratov': N_('Europe / Saratov'),
	'Europe/Simferopol': N_('Europe / Simferopol'),
	'Europe/Skopje': N_('Europe / Skopje'),
	'Europe/Sofia': N_('Europe / Sofia'),
	'Europe/Stockholm': N_('Europe / Stockholm'),
	'Europe/Tallinn': N_('Europe / Tallinn'),
	'Europe/Tirane': N_('Europe / Tirane'),
	'Europe/Tiraspol': N_('Europe / Tiraspol'),
	'Europe/Ulyanovsk': N_('Europe / Ulyanovsk'),
	'Europe/Uzhgorod': N_('Europe / Uzhgorod'),
	'Europe/Vaduz': N_('Europe / Vaduz'),
	'Europe/Vatican': N_('Europe / Vatican'),
	'Europe/Vienna': N_('Europe / Vienna'),
	'Europe/Vilnius': N_('Europe / Vilnius'),
	'Europe/Volgograd': N_('Europe / Volgograd'),
	'Europe/Warsaw': N_('Europe / Warsaw'),
	'Europe/Zagreb': N_('Europe / Zagreb'),
	'Europe/Zaporozhye': N_('Europe / Zaporozhye'),
	'Europe/Zurich': N_('Europe / Zurich'),
	'Factory': N_('Factory'),
	'GB': N_('GB'),
	'GB-Eire': N_('GB-Eire'),
	'GMT': N_('GMT'),
	'GMT+0': N_('GMT+0'),
	'GMT-0': N_('GMT-0'),
	'GMT0': N_('GMT0'),
	'Greenwich': N_('Greenwich'),
	'HST': N_('HST'),
	'Hongkong': N_('Hongkong'),
	'Iceland': N_('Iceland'),
	'Indian/Antananarivo': N_('Indian / Antananarivo'),
	'Indian/Chagos': N_('Indian / Chagos'),
	'Indian/Christmas': N_('Indian / Christmas'),
	'Indian/Cocos': N_('Indian / Cocos'),
	'Indian/Comoro': N_('Indian / Comoro'),
	'Indian/Kerguelen': N_('Indian / Kerguelen'),
	'Indian/Mahe': N_('Indian / Mahe'),
	'Indian/Maldives': N_('Indian / Maldives'),
	'Indian/Mauritius': N_('Indian / Mauritius'),
	'Indian/Mayotte': N_('Indian / Mayotte'),
	'Indian/Reunion': N_('Indian / Reunion'),
	'Iran': N_('Iran'),
	'Israel': N_('Israel'),
	'Jamaica': N_('Jamaica'),
	'Japan': N_('Japan'),
	'Kwajalein': N_('Kwajalein'),
	'Libya': N_('Libya'),
	'MET': N_('MET'),
	'MST': N_('MST'),
	'MST7MDT': N_('MST7MDT'),
	'Mexico/BajaNorte': N_('Mexico / BajaNorte'),
	'Mexico/BajaSur': N_('Mexico / BajaSur'),
	'Mexico/General': N_('Mexico / General'),
	'NZ': N_('NZ'),
	'NZ-CHAT': N_('NZ-CHAT'),
	'Navajo': N_('Navajo'),
	'PRC': N_('PRC'),
	'PST8PDT': N_('PST8PDT'),
	'Pacific/Apia': N_('Pacific / Apia'),
	'Pacific/Auckland': N_('Pacific / Auckland'),
	'Pacific/Bougainville': N_('Pacific / Bougainville'),
	'Pacific/Chatham': N_('Pacific / Chatham'),
	'Pacific/Chuuk': N_('Pacific / Chuuk'),
	'Pacific/Easter': N_('Pacific / Easter'),
	'Pacific/Efate': N_('Pacific / Efate'),
	'Pacific/Enderbury': N_('Pacific / Enderbury'),
	'Pacific/Fakaofo': N_('Pacific / Fakaofo'),
	'Pacific/Fiji': N_('Pacific / Fiji'),
	'Pacific/Funafuti': N_('Pacific / Funafuti'),
	'Pacific/Galapagos': N_('Pacific / Galapagos'),
	'Pacific/Gambier': N_('Pacific / Gambier'),
	'Pacific/Guadalcanal': N_('Pacific / Guadalcanal'),
	'Pacific/Guam': N_('Pacific / Guam'),
	'Pacific/Honolulu': N_('Pacific / Honolulu'),
	'Pacific/Johnston': N_('Pacific / Johnston'),
	'Pacific/Kanton': N_('Pacific / Kanton'),
	'Pacific/Kiritimati': N_('Pacific / Kiritimati'),
	'Pacific/Kosrae': N_('Pacific / Kosrae'),
	'Pacific/Kwajalein': N_('Pacific / Kwajalein'),
	'Pacific/Majuro': N_('Pacific / Majuro'),
	'Pacific/Marquesas': N_('Pacific / Marquesas'),
	'Pacific/Midway': N_('Pacific / Midway'),
	'Pacific/Nauru': N_('Pacific / Nauru'),
	'Pacific/Niue': N_('Pacific / Niue'),
	'Pacific/Norfolk': N_('Pacific / Norfolk'),
	'Pacific/Noumea': N_('Pacific / Noumea'),
	'Pacific/Pago_Pago': N_('Pacific / Pago Pago'),
	'Pacific/Palau': N_('Pacific / Palau'),
	'Pacific/Pitcairn': N_('Pacific / Pitcairn'),
	'Pacific/Pohnpei': N_('Pacific / Pohnpei'),
	'Pacific/Ponape': N_('Pacific / Ponape'),
	'Pacific/Port_Moresby': N_('Pacific / Port Moresby'),
	'Pacific/Rarotonga': N_('Pacific / Rarotonga'),
	'Pacific/Saipan': N_('Pacific / Saipan'),
	'Pacific/Samoa': N_('Pacific / Samoa'),
	'Pacific/Tahiti': N_('Pacific / Tahiti'),
	'Pacific/Tarawa': N_('Pacific / Tarawa'),
	'Pacific/Tongatapu': N_('Pacific / Tongatapu'),
	'Pacific/Truk': N_('Pacific / Truk'),
	'Pacific/Wake': N_('Pacific / Wake'),
	'Pacific/Wallis': N_('Pacific / Wallis'),
	'Pacific/Yap': N_('Pacific / Yap'),
	'Poland': N_('Poland'),
	'Portugal': N_('Portugal'),
	'ROC': N_('ROC'),
	'ROK': N_('ROK'),
	'Singapore': N_('Singapore'),
	'Turkey': N_('Turkey'),
	'UCT': N_('UCT'),
	'US/Alaska': N_('US / Alaska'),
	'US/Aleutian': N_('US / Aleutian'),
	'US/Arizona': N_('US / Arizona'),
	'US/Central': N_('US / Central'),
	'US/East-Indiana': N_('US / East-Indiana'),
	'US/Eastern': N_('US / Eastern'),
	'US/Hawaii': N_('US / Hawaii'),
	'US/Indiana-Starke': N_('US / Indiana-Starke'),
	'US/Michigan': N_('US / Michigan'),
	'US/Mountain': N_('US / Mountain'),
	'US/Pacific': N_('US / Pacific'),
	'US/Samoa': N_('US / Samoa'),
	'UTC': N_('UTC'),
	'Universal': N_('Universal'),
	'W-SU': N_('W-SU'),
	'WET': N_('WET'),
	'Zulu': N_('Zulu'),
}
