"""Core Awqati concepts with no platform dependencies."""

from .models import (
	Coordinates,
	DomainEvent,
	Instant,
	Location,
	LocationChanged,
	LocationDetectionFailure,
	LocationDetectionResult,
	LocationState,
	LocationStatus,
)
from .prayer import (
	AsrMethod,
	CalculationMethod,
	CalculationMethodDefinition,
	CountryMethodResolver,
	HighLatitudeRule,
	MAX_USER_CORRECTION_MINUTES,
	MIN_USER_CORRECTION_MINUTES,
	NEAREST_LATITUDE,
	PrayerCalculationError,
	PrayerCalculationMetadata,
	PrayerCalculationRequest,
	PrayerCalculator,
	PrayerCorrections,
	PrayerName,
	PrayerTimes,
	RamadanContextRequired,
	SUNRISE_SUNSET_ANGLE,
)

__all__ = [
	"AsrMethod",
	"CalculationMethod",
	"CalculationMethodDefinition",
	"Coordinates",
	"CountryMethodResolver",
	"DomainEvent",
	"HighLatitudeRule",
	"Instant",
	"Location",
	"LocationChanged",
	"LocationDetectionFailure",
	"LocationDetectionResult",
	"LocationState",
	"LocationStatus",
	"MAX_USER_CORRECTION_MINUTES",
	"MIN_USER_CORRECTION_MINUTES",
	"NEAREST_LATITUDE",
	"PrayerCalculationError",
	"PrayerCalculationMetadata",
	"PrayerCalculationRequest",
	"PrayerCalculator",
	"PrayerCorrections",
	"PrayerName",
	"PrayerTimes",
	"RamadanContextRequired",
	"SUNRISE_SUNSET_ANGLE",
]
